"""add_must_change_password

Revision ID: 60354633785d
Revises: d4e5f6a7b8c9
Create Date: 2026-05-29 08:23:42.272211

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '60354633785d'
down_revision: Union[str, None] = 'd4e5f6a7b8c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('support_evidence')
    op.alter_column('project_plans', 'plan_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.add_column('villages', sa.Column('must_change_password', sa.Boolean(), nullable=False, server_default='true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('villages', 'must_change_password')
    op.alter_column('project_plans', 'plan_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.create_table('support_evidence',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('village_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('doc_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('filename', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('file_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('uploaded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['village_id'], ['villages.id'], name=op.f('support_evidence_village_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('support_evidence_pkey'))
    )
    # ### end Alembic commands ###
